name: verifying-key check

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-bash-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          # use the private key and app id secret that we created in the Github App section
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Reconfigure git to use HTTP authentication
        # Fix our git override using the generated token from the create_token step + use the "x-access-token".
        run: |
          git config --global url."https://x-access-token:${{ steps.create_token.outputs.token }}@github.com".insteadOf  https://github.com
      - name: Fetch and compare vkeys
        run: |
          sh ./vkey.sh send_quadra temp2/send_quadra
          if diff -rq temp2/send_quadra/send_quadra elusiv/src/proof/vkeys/send_quadra ; then
            echo "Vkeys up to date"
          else
            echo "Vkeys not up to date"
            exit 1
          fi
